kind: Deployment
apiVersion: apps/v1
metadata:
  name: bg-search
spec:
  selector:
    matchLabels:
      app: bg-search
  template:
    metadata:
      labels:
        app: bg-search
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: default
          image: ghcr.io/nafarlee/bg-search:556e9a8e995851accf0680b5b2c2a30d50418110
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 75m
              memory: 94371840
          env:
            - name: MIRROR_BASE_URL
              value: https://mirror.bgs.nafarlee.dev
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: database
            - name: BGG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bgg-api-key
                  key: bgg-api-key
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: postgres-password
