namespace: bg-search

resources:
  - namespace.yaml
  - bg-search-deployment.yaml
  - bg-search-service.yaml
  - bg-search-ingress.yaml
  - mirror-deployment.yaml
  - mirror-service.yaml
  - mirror-ingress.yaml
  - database-statefulset.yaml
  - database-service.yaml
  - pull-deployment.yaml
  - pull-plays-deployment.yaml
  - refresh-play-medians-cronjob.yaml
  - set-game-id-cliff-cronjob.yaml

secretGenerator:
  - name: cloud-storage-key
    files:
      - cloud-storage-key=cloud-storage-key.secret
  - name: postgres-password
    files:
      - postgres-password=postgres-password.secret
  - name: bgg-api-key
    files:
      - bgg-api-key=bgg-api-key.secret

configMapGenerator:
  - name: db-init
    files:
      - db.sql

images:
  - name: ghcr.io/nafarlee/bg-search-web
    newTag: 8f1e1a8087e1616894edc3189e0153b7a04c3402
  - name: ghcr.io/nafarlee/bg-search-pull-games
    newTag: 8f1e1a8087e1616894edc3189e0153b7a04c3402
  - name: ghcr.io/nafarlee/bg-search-pull-plays
    newTag: 8f1e1a8087e1616894edc3189e0153b7a04c3402
  - name: ghcr.io/nafarlee/bg-search-set-game-id-cliff
    newTag: 8f1e1a8087e1616894edc3189e0153b7a04c3402
