kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mirror
  annotations:
    cert-manager.io/cluster-issuer: "lets-encrypt"
spec:
  ingressClassName: nginx
  rules:
    - host: mirror.bgs.nafarlee.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mirror
                port:
                  number: 80
  tls:
    - secretName: mirror-tls
      hosts:
        - mirror.bgs.nafarlee.dev
