kind: Deployment
apiVersion: apps/v1
metadata:
  name: pull-plays
spec:
  selector:
    matchLabels:
      app: pull-plays
  template:
    metadata:
      labels:
        app: pull-plays
        type: cron
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: default
          image: ghcr.io/nafarlee/bg-search-pull-plays:e5746026a492a602ea649bd98a28de773b4a12c3
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: database
            - name: BGG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bgg-api-key
                  key: bgg-api-key
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: postgres-password
